version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ebdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  web:
    image: notfoundsam/php-apache-laravel:latest
    ports:
      - "9090:80"
    deploy:
      replicas: 2

volumes:
  db-data:
